/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MakerId = IDL.Nat;
export const Maker = IDL.Record({
  'id' : MakerId,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
  'isActive' : IDL.Bool,
  'whatsappNumber' : IDL.Text,
  'state' : IDL.Text,
  'story' : IDL.Text,
});
export const ProductId = IDL.Nat;
export const OrderId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'mrp' : IDL.Float64,
  'usp' : IDL.Text,
  'preparationMethod' : IDL.Text,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'makerId' : MakerId,
  'sellingPrice' : IDL.Float64,
  'description' : IDL.Text,
  'state' : IDL.Text,
  'imageUrl' : IDL.Text,
  'minBatchKg' : IDL.Float64,
  'category' : IDL.Text,
  'ingredients' : IDL.Vec(IDL.Text),
});
export const TestimonialId = IDL.Nat;
export const Time = IDL.Int;
export const Testimonial = IDL.Record({
  'id' : TestimonialId,
  'customerName' : IDL.Text,
  'createdAt' : Time,
  'message' : IDL.Text,
  'rating' : IDL.Nat,
  'location' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'pending' : IDL.Null,
  'dispatched' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'customerPhone' : IDL.Text,
  'whatsappOrderText' : IDL.Text,
  'createdAt' : Time,
  'makerId' : MakerId,
  'productId' : ProductId,
  'customerAddress' : IDL.Text,
  'advanceAmount' : IDL.Float64,
  'totalAmount' : IDL.Float64,
  'quantityKg' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const StateCount = IDL.Record({ 'count' : IDL.Nat, 'state' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMaker' : IDL.Func([Maker], [MakerId], []),
  'createOrder' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [OrderId],
      [],
    ),
  'createProduct' : IDL.Func([Product], [ProductId], []),
  'createTestimonial' : IDL.Func([Testimonial], [TestimonialId], []),
  'deleteMaker' : IDL.Func([MakerId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'deleteTestimonial' : IDL.Func([TestimonialId], [], []),
  'getAllMakers' : IDL.Func([], [IDL.Vec(Maker)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMakerWithProducts' : IDL.Func(
      [MakerId],
      [IDL.Opt(IDL.Tuple(Maker, IDL.Vec(Product)))],
      ['query'],
    ),
  'getMakersByState' : IDL.Func([IDL.Text], [IDL.Vec(Maker)], ['query']),
  'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProductsByState' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getStatesListWithProductCounts' : IDL.Func(
      [],
      [IDL.Vec(StateCount)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedData' : IDL.Func([], [], []),
  'updateMaker' : IDL.Func([Maker], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateTestimonial' : IDL.Func([Testimonial], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MakerId = IDL.Nat;
  const Maker = IDL.Record({
    'id' : MakerId,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
    'isActive' : IDL.Bool,
    'whatsappNumber' : IDL.Text,
    'state' : IDL.Text,
    'story' : IDL.Text,
  });
  const ProductId = IDL.Nat;
  const OrderId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'mrp' : IDL.Float64,
    'usp' : IDL.Text,
    'preparationMethod' : IDL.Text,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'makerId' : MakerId,
    'sellingPrice' : IDL.Float64,
    'description' : IDL.Text,
    'state' : IDL.Text,
    'imageUrl' : IDL.Text,
    'minBatchKg' : IDL.Float64,
    'category' : IDL.Text,
    'ingredients' : IDL.Vec(IDL.Text),
  });
  const TestimonialId = IDL.Nat;
  const Time = IDL.Int;
  const Testimonial = IDL.Record({
    'id' : TestimonialId,
    'customerName' : IDL.Text,
    'createdAt' : Time,
    'message' : IDL.Text,
    'rating' : IDL.Nat,
    'location' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'pending' : IDL.Null,
    'dispatched' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'customerPhone' : IDL.Text,
    'whatsappOrderText' : IDL.Text,
    'createdAt' : Time,
    'makerId' : MakerId,
    'productId' : ProductId,
    'customerAddress' : IDL.Text,
    'advanceAmount' : IDL.Float64,
    'totalAmount' : IDL.Float64,
    'quantityKg' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StateCount = IDL.Record({ 'count' : IDL.Nat, 'state' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMaker' : IDL.Func([Maker], [MakerId], []),
    'createOrder' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [OrderId],
        [],
      ),
    'createProduct' : IDL.Func([Product], [ProductId], []),
    'createTestimonial' : IDL.Func([Testimonial], [TestimonialId], []),
    'deleteMaker' : IDL.Func([MakerId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'deleteTestimonial' : IDL.Func([TestimonialId], [], []),
    'getAllMakers' : IDL.Func([], [IDL.Vec(Maker)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMakerWithProducts' : IDL.Func(
        [MakerId],
        [IDL.Opt(IDL.Tuple(Maker, IDL.Vec(Product)))],
        ['query'],
      ),
    'getMakersByState' : IDL.Func([IDL.Text], [IDL.Vec(Maker)], ['query']),
    'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByState' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getStatesListWithProductCounts' : IDL.Func(
        [],
        [IDL.Vec(StateCount)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedData' : IDL.Func([], [], []),
    'updateMaker' : IDL.Func([Maker], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateTestimonial' : IDL.Func([Testimonial], [], []),
  });
};

export const init = ({ IDL }) => { return []; };