/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Maker {
  'id' : MakerId,
  'bio' : string,
  'name' : string,
  'photoUrl' : string,
  'isActive' : boolean,
  'whatsappNumber' : string,
  'state' : string,
  'story' : string,
}
export type MakerId = bigint;
export interface Order {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'customerPhone' : string,
  'whatsappOrderText' : string,
  'createdAt' : Time,
  'makerId' : MakerId,
  'productId' : ProductId,
  'customerAddress' : string,
  'advanceAmount' : number,
  'totalAmount' : number,
  'quantityKg' : number,
}
export type OrderId = bigint;
export type OrderStatus = { 'preparing' : null } |
  { 'pending' : null } |
  { 'dispatched' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Product {
  'id' : ProductId,
  'mrp' : number,
  'usp' : string,
  'preparationMethod' : string,
  'name' : string,
  'isAvailable' : boolean,
  'makerId' : MakerId,
  'sellingPrice' : number,
  'description' : string,
  'state' : string,
  'imageUrl' : string,
  'minBatchKg' : number,
  'category' : string,
  'ingredients' : Array<string>,
}
export type ProductId = bigint;
export interface StateCount { 'count' : bigint, 'state' : string }
export interface Testimonial {
  'id' : TestimonialId,
  'customerName' : string,
  'createdAt' : Time,
  'message' : string,
  'rating' : bigint,
  'location' : string,
}
export type TestimonialId = bigint;
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMaker' : ActorMethod<[Maker], MakerId>,
  'createOrder' : ActorMethod<
    [ProductId, string, string, string, number, number, string],
    OrderId
  >,
  'createProduct' : ActorMethod<[Product], ProductId>,
  'createTestimonial' : ActorMethod<[Testimonial], TestimonialId>,
  'deleteMaker' : ActorMethod<[MakerId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'deleteTestimonial' : ActorMethod<[TestimonialId], undefined>,
  'getAllMakers' : ActorMethod<[], Array<Maker>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMakerWithProducts' : ActorMethod<
    [MakerId],
    [] | [[Maker, Array<Product>]]
  >,
  'getMakersByState' : ActorMethod<[string], Array<Maker>>,
  'getOrderById' : ActorMethod<[OrderId], [] | [Order]>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getProductsByState' : ActorMethod<[string], Array<Product>>,
  'getStatesListWithProductCounts' : ActorMethod<[], Array<StateCount>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'updateMaker' : ActorMethod<[Maker], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateTestimonial' : ActorMethod<[Testimonial], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];